### PR TITLE
Fix race condition when starting Xvfb

### LINKED ISSUE #75: Race condition when starting Xvfb
Here's what can happen: 

 * Two processes, A and B, try to use Headless.new().
 * Process A "wins" and gains the lock on /tmp/.X-#{display}-lock
 * Process B loses. Xvfb errors and exits immediately.
 * ensure_xvfb_is_running calls xvfb_running?
 * xvfb_running? finds a display lock file, and thinks it's ours. It
   erroneously reports that our process is running.

Then, Headless goes on using that display number, even though it's not the process we started. **Even if we set `resuse: false`.**
When process A destroys its Xvfb, all of process B's X11 programs die unexpectedly.

When using Selenium, this usually expresses itself as an EOFError. The Selenium web driver loses its connection to the web browser when it's killed.

### PR DESCRIPTION
**Pull request by NfNitLoop**
This resolves #75

### CODE REVIEW

**Comment by NfNitLoop** [comment]
So, it looks like the ruby 1.x and 2.2 testers failed to install some dependencies. 

The ruby2 tests are failing because the specs are trying to fake out the old `xvfb_running?` by mocking CliUtil methods.  But the updated version of `xvfb_running?` doesn't even get that far. Since the spec is mocking launch_xvfb, `@pid` never gets sed, and `xvfb_running?` will always return false.

I'm scratching my head a bit at the easiest way to update the tests to handle this.

**Comment by NfNitLoop** [comment]
Ooh, I see. I accidentally changed the signature of `xvfb_running?`. It used to return true if there's an Xvfb running for `display`, even if we didn't start it. Which is the desired behavior if we want to re-use that display. Fixing!

**Comment by NfNitLoop** [comment]
Yay!  Ruby2 tests are passing. 

The other 2 environments still seem to be having problems installing their dependencies. I don't think that's due to anything I changed, but please poke me if there's anything I can do to help get this ready for merge!

Thanks for writing Headless!

**Comment by erkki** [comment]
Anything possible to do here to help with getting this accepted/rejected?

**Comment by NfNitLoop** [comment]
I'm still around and willing to make any changes necessary to get this merged.  (In the meantime, we're just using the fixed version over in https://github.com/NfNitLoop/headless/tree/fix-launch-race.)

**Comment by erkki** [comment]
Good to know, we're also gonna need to either use a workaround or a custom patch as we're seeing this (or something related) in the wild, so wanted to add an data-point and offer help in any way to get to an resolution.

**Comment by leonid-shevtsov** [comment]
@NfNitLoop @erkki I'll fix the tests and merge it this weekend.

**Comment by erkki** [comment]
@leonid-shevtsov much appreciated!

**Comment by twKrash** [comment]
Any update here?

**Comment by leonid-shevtsov** [comment]
As it turned out, bundler on Travis was causing issues and that's the only reason the build was failing.

Merged and released in version 2.2.3.

**Pull request merged**
